# Generated by Django 3.2.8 on 2021-10-27 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripecustomer',
            name='stripePaymentMethodId',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
